package com.example.kotlinpractice.utilss

object PARAMS {

    // API Headers
    const val HEADER_X_API_KEY = "x-api-key"
    const val HEADER_TOKEN = "header-token"
    const val HEADER_APP_VERSION = "app-version"
    const val HEADER_DEVICE_TYPE = "device-type"
    const val HEADER_DEVICE_TOKEN = "device-token"
    const val HEADER_ACCEPT = "Accept"
    const val HEADER_CONTENT_TYPE = "Content-Type"
    const val HEADER_ASC_POS_ID = "Asc.PosID"
    const val HEADER_X_FORWARDED_FOR = "x-forwarded-for"
    const val HEADER_USER_AGENT = "user-agent"
    const val HEADER_AUTHORIZATION = "Authorization"
    const val HEADER_SOAP_ACTION = "SoapAction"
    const val HEADER_ASC_APPNAME = "Asc.AppName"

    // API Parameters
    const val TAG_REQUEST_DYNAMIC_FIELDS = "RequestDynamicFields"
    const val TAG_MOBILE_NO = "MobileNo"
    const val TAG_SMS_SUBSCRIPTION = "smsSubscription"
    const val TAG_MAIL_LIST = "mailingLists"
    const val LUCKY_DEEP_ID = "LuckyDipId"
    const val INCLUDE_CHANCES = "IncludeChances"
    const val TAG_FILTER = "Filter"
    const val TAG_VOUCHER_TYPE_FILTER = "VoucherTypeFilter"
    const val TAG_OUTLET = "Outlet"
    const val TAG_MALL = "Mall"
    const val TAG_SKIP_COUNT = "SkipCount"
    const val TAG_MAX_RESULT_COUNT = "MaxResultCount"
    const val VOUCHER_TYPE_CODES = "VoucherTypeCodes"
    const val SPECIAL_VOUCHER_TYPES = "ShowSpecialVoucherTypes"
    const val INCLUDE_EXPIRED = "IncludeExpired"
    const val INCLUDE_STATUS = "IncludeStatus"
    const val TAG_TRANSACT_DATE_FROM = "TransactDateFrom"
    const val TAG_TRANSACT_DATE_TO = "TransactDateTo"
    const val TAG_SUBMISSION_START_DATE = "SubmissionStartDate"
    const val TAG_SUBMISSION_END_DATE = "SubmissionEndDate"
    const val TAG_START_TRANSACT_DATE = "StartTransactDate"
    const val TAG_END_TRANSACT_DATE = "EndTransactDate"
    const val TAG_MODE_FILTERS = "ModeFilters"
    const val TAG_ID = "Id"
    const val TAG_OUTLET_CODE = "OutletCode"
    const val TAG_BLAST_ID = "blastID"
    const val TAG_BLAST_HEADER_ID = "blastHeaderID"


    const val ARG_NAME = "name"
    const val ARG_EMAIL = "email"
    const val ARG_TOPIC = "topic"
    const val ARG_COMMENT = "comment"
    const val ARG_GENDER = "gender"
    const val ARG_DOB = "birthday"

    // Intent Parameters
    const val INTENT_WEB_URL = "webUrl"
    const val INTENT_WEB_VIEW_TITLE = "titleName"
    const val INTENT_STORE_SLUG = "storeSlug"
    const val INTENT_STORE_SORT_BY = "storeSortBy"
    const val INTENT_VOUCHER_SORT_BY = "voucherSortBy"
    const val INTENT_VOUCHER_TYPE_CODE = "voucherTypeCode"
    const val INTENT_VOUCHER_FILTER_BY_STATUS = "voucherFilterByStatus"
    const val INTENT_FILTER_COUNT = "filterCount"
    const val INTENT_STORE_SORT_BY_NAME = "storeSortByName"
    const val INTENT_STORE_TYPES_LIST = "storeTypeList"
    const val INTENT_VOUCHER_ITEM = "voucherItem"
    const val INTENT_OVERLY_TEXT = "overlayText"
    const val INTENT_STORE_CATEGORY_LIST = "storeCategoryList"
    const val INTENT_STORE_SLUG_LIST = "storeSlugList"
    const val INTENT_IS_RESET_FROM_EMAIL = "isResetFromEmail"
    const val INTENT_IS_LOGIN_WITH_EMAIL = "isLoginWithEmail"
    const val INTENT_QA_LIST = "qaList"
    const val INTENT_CACHED_VIDEO_INDEX = "cachedVideoIndex"
    const val INTENT_IU_ITEM = "iuItem"
    const val INTENT_PARKING_INFO = "parkingInfo"
    const val INTENT_IS_HTML_CONTENT = "isHtmlContent"
    const val INTENT_GAME_URL = "gameURL"
    const val INTENT_GAME_TERMS = "isGameTermsCondition"
    const val INTENT_LUCKY_DIP_ID = "crm_game_id"
    const val INTENT_IS_FROM_KIDS_CLUB = "isFromKidsClub"
    const val INTENT_IS_VERIFY_ACCOUNT = "isVerifyAccount"
    const val INTENT_VIP_PARKING = "vipParking"
    const val INTENT_FREE_2HR_PARKING = "free2HrParking"
    const val INTENT_NOTIFICATION_TITLE = "notificationTitle"
    const val INTENT_NOTIFICATION_DATE_TIME = "notificationDateTime"
    const val INTENT_PRIVACY_POLICY = "isFromPrivacyPPolicy"
    const val INTENT_KIDS_CLUB_TERMS = "isFromKidsClubTerms"
    const val INTENT_TERMS_AND_CONDITION = "isFromTermsAndCondition"
    const val INTENT_CATALOGUE_DETAIL_TERMS = "isCatalogueTerms"
    const val INTENT_VOUCHER_DETAIL_TERMS = "isVoucherDetailTerms"
    const val INTENT_PARKING_DETAIL_TERMS = "isParkingDetailTerms"
    const val INTENT_STORE_WAY_FINDING = "isStoreWayFinding"
    const val INTENT_PARKING_RATES = "isParkingRates"
    const val INTENT_NOTIFICATION_MESSAGE = "notificationMessage"
    const val INTENT_CATALOGUE_CATEGORY_LIST = "catalogueCategoryList"
    const val INTENT_CATALOGUE_CAMPAIGN_LIST = "catalogueCampaignList"
    const val INTENT_CATALOGUE_TYPES_LIST = "catalogueTypeList"
    const val INTENT_CATALOGUE_GROUP_LIST = "catalogueGroupList"
    const val INTENT_TOTAL_FILTER_COUNT = "totalFilterCount"
    const val INTENT_CATALOGUE_SORT_BY_NAME = "catalogueSortByName"
    const val INTENT_CATALOGUE_SORT_BY = "catalogueSortBy"
    const val INTENT_IS_CATALOGUE_FILTER = "isCatalogueFilter"
    const val INTENT_CATALOGUE_CODE = "catalogueCode"
    const val INTENT_CMS_CATALOGUE_TYPE = "cmsCatalogueType"
    const val INTENT_CMS_CATALOGUE_TITLE = "cmsCatalogueTitle"
    const val INTENT_CMS_CATALOGUE_UNIT_PRICE = "cmsCatalogueUnitPrice"
    const val INTENT_CATALOGUE_QUANTITY = "cmsCatalogueQuantity"
    const val INTENT_CATALOGUE_TOTAL_PRICE = "cmsCatalogueTotalPrice"
    const val INTENT_POINT_REF_ID = "pointsRefId"
    const val INTENT_VOUCHER_REF_ID = "voucherRefId"
    const val IS_FROM_PAY_WITH_WALLET = "isFromPayWithWallet"
    const val INTENT_IS_FROM_PUSH = "isFromPush"
    const val INTENT_NOTIFICATION_DATA = "notificationData"
    const val INTENT_IS_FROM_CONVERT_PHYSICAL_VOUCHER = "isFromConvertPhysicalVoucher"
    const val INTENT_IS_FROM_MEMBER_BENEFIT = "isFromMemberBenefit"
    const val INTENT_IS_FROM_KIDS_CLUB_BENEFIT = "isFromKidsClubBenefit"

}